title: Clint Harvey
description: This is my living resume. I try to keep this as updated as possible when I learn new things or have a new hilight project that I'm allowed to talk about publicly.
show_downloads: true
google_analytics: UA-5217991-1
theme: jekyll-theme-slate
