title: Clint Harvey
description: This is my living resume. I keep it updated as I learn new things or have new projects that I'm allowed to talk about publicly.
show_downloads: true
google_analytics: UA-5217991-1
theme: jekyll-theme-slate
